# Generated by Django 2.2.6 on 2020-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200220_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='self_check',
            field=models.BooleanField(default=False),
        ),
    ]
