# Generated by Django 2.2.6 on 2020-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='crd',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
