# Generated by Django 2.2.6 on 2020-04-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_crd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
